
import numpy as np
import random
import math
import colorama
from colorama import Fore

# lst =[]
# for i in range(0, 5):
#     l = random.randint(1, 15)
#     # if l%5 == 0:
#     #     lst.append(l)
#     lst.append(l)

print('WELCOME TO GUESSING GAME CREATED BY KLAUS PEACE')
yourName = input('Enter Your Name: ')
print('\nThank you for Signing up', Fore.BLUE + f'{yourName}\n\n')
print(Fore.WHITE + 'Game Procedure and Rules:')
print('1. You are provided with a list of 15 random whole numbers between 0 and 100 exclusive')
print('2. You are required to choose 5 numbers from the list')
print('3. Your List need to match the random list of 5 numbers that will be generated by the computer')
print('4. The numbers must match both in magnitude and position in the list')
print('5. Your points scored equals the number of matched numbers multiplied by 2')
print('6. You win (n!-1) US dollars where n is the number of points')
print('7. You can only win 0, 2, 4, 6, 8, 10 points')
print('(0 point [0 correct match]-> 0!-1 = $ 0) ')
print('(2 points [1 correct match]-> 2!-1 = $ 1) ')
print('(4 points [2 correct matches]-> 4!-1 = $ 23) ')
print('(6 points [3 correct matches]-> 6!-1 = $ 719) ')
print('(8 points [4 correct matches]-> 8!-1 = $ 40,319) ')
print('(10 points [5 correct matches]-> 10!-1 = $ 3,628,799) ')
input("Press Enter to Continue: ")
print('\n\n')

def guessGame():
    l1 = random.sample(range(1, 99), 15)
    print('Random List: ', l1)

    print('Select Five (5) numbers in the above list in the correct order.')
    myList = input('Enter numbers (No repetition): ').split()
    myList = [int(x) for x in myList]
    print('\n')

    l2 = random.sample(l1, k=5)

    count = 0
    for i in range(5):
        if myList[i] == l2[i]:
            count += 1

    points = 0

    if (count == 5):
        print(Fore.GREEN + 'You won!\n')
        won = True
    elif (count == 4):
        print(Fore.GREEN + 'You Won!\n')
        won = False
    elif (count == 3):
        print(Fore.GREEN + 'You Won!\n')
        won = False
    elif (count == 2):
        print(Fore.GREEN + 'You Won! \n')
        won = False
    elif (count == 1):
        print(Fore.GREEN + 'You Won!\n')
        won = False
    else:
        print(Fore.RED + 'You Lost!\n')
        won = False
    points += count*2

    print(Fore.WHITE + 'Your List: ', myList)
    print("Correct List: ", l2, '\n')

    print('Number of Correct Matches: ', count)
    print('Number of Points: ', points)
    amount = math.factorial(points) - 1
    print('Amount won: $', amount)

    dec = input('Do You Want to Continue Playing? (y/n): ')


    while dec.lower() != "y" and dec.lower() != "n":
        dec = input('Do You Want to Continue Playing? (y/n): ')
        if dec.lower() == "y":
            guessGame()
        elif dec.lower() == "n":
            exit()

guessGame()